### PR TITLE
be Scala 2.13 friendly

### PR DESCRIPTION
**Pull request by SethTisue**
for the Scala 2.13 community build

### CODE REVIEW

**Comment by fommil** [comment]
That's very exciting!

**Comment by SethTisue** [comment]
@fommil oops, I should have submitted this at ensime/pcplod instead, right? can you merge it there? sorry

**Comment by fommil** [comment]
yeah, I didn't even notice. I'll give you perms to merge these sort of things. I'm away from a computer for the rest of the day.

**Comment by SethTisue** [comment]
thx. new PR https://github.com/ensime/pcplod/pull/16

**Pull request merged**
